config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users, :articles, :reports
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [:create] do
        collection do
          get 'reports', 'articles', 'show'
          post 'forgot'
          patch :update
        end
      end
      resources :accesstokens, only: [:create]
      resources :articles, only: [:index, :create] do
        post 'know'
        post 'comments'
      end
      resources :reports, only: [:create]
    end
  end

end

app/models/admin/article.rb
class Admin::Article < Article
end

app/models/article.rb
class Article < ActiveRecord::Base
  # Scope macros
  scope :by_newest, -> { order(created_at: :desc) }
  
  # Concerns macros

  # Constants

  # Attributes related macros

  # Association macros
  belongs_to :user
  has_many :knows, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  # Validation macros
  validates :content, presence: true

  # Callbacks

  # other

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  before_action :set_admin_article, only: [:show, :edit, :update, :destroy]

  # GET /admin/articles
  # GET /admin/articles.json
  def index
    @admin_articles = Admin::Article.all
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.json
  def show
  end

  # GET /admin/articles/new
  def new
    @admin_article = Admin::Article.new
  end

  # GET /admin/articles/1/edit
  def edit
  end

  # POST /admin/articles
  # POST /admin/articles.json
  def create
    @admin_article = Admin::Article.new(admin_article_params)

    respond_to do |format|
      if @admin_article.save
        format.html { redirect_to @admin_article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @admin_article }
      else
        format.html { render :new }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/articles/1
  # PATCH/PUT /admin/articles/1.json
  def update
    respond_to do |format|
      if @admin_article.update(admin_article_params)
        format.html { redirect_to @admin_article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_article }
      else
        format.html { render :edit }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.json
  def destroy
    @admin_article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_article
      @admin_article = Admin::Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_article_params
      params.require(:admin_article).permit(:user, :content, :created_at, :region)
    end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::BaseController
  before_action :authenticate!
  before_action :set_article, only: [:know, :comments]

  def index
    @articles = Article.by_newest
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      render :show, status: :created
    else
      render json: @article.errors, status: :unprocessable_entity
    end
  end

  def know
    @article.knows.create(user: current_user)
    render :show, status: :created
  end

  def comments
    comment = @article.comments.new(comment_params)
    comment.user = current_user

    if comment.save
      render :show, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  private
    def set_article
      @article = Article.find(params[:article_id])
    end

    def article_params
      params.require(:article).permit(:content)
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/views/admin/articles/_form.html.slim
= form_for(@admin_article, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @admin_article.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@admin_article.errors.count,"error")} prohibited this admin_article from being saved:"
      ul
        - @admin_article.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :region, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :region, class: "form-control"
  .form-group
    = f.label :user_id, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :user_id, class: "form-control"
  .form-group
    = f.label :content, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :content, class: "form-control"
  .form-group
    = f.label :created_at, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :created_at, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/admin/articles/edit.html.slim
.page-header
  = link_to admin_articles_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @admin_article, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | admin_article

= render 'form'

app/views/admin/articles/index.html.slim
.page-header
  = link_to new_admin_article_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Article
  h1
    | Listing admin_articles

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | User
        th
          | Content
        th
          | Created at
        th
        th
        th
    tbody
      - @admin_articles.each do | admin_article |
        tr
          td
            = link_to admin_article.user, admin_user_path(admin_article)
          td
            = admin_article.content
          td
            = admin_article.created_at
          td
            = link_to 'Show', admin_article
          td
            = link_to 'Edit', edit_admin_article_path(admin_article) 
          td
            = link_to 'Destroy', admin_article, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/admin/articles/new.html.slim
.page-header
  = link_to admin_articles_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | admin_article

= render 'form'

app/views/admin/articles/show.html.slim
.page-header
  = link_to admin_articles_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_admin_article_path(@admin_article), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show admin_article
dl.dl-horizontal
  dt
    | User:
  dd
    = @admin_article.user
  dt
    | Content:
  dd
    = @admin_article.content
  dt
    | Created at:
  dd
    = @admin_article.created_at

  dd
    table.table
      - @admin_article.comments.each do |comment|
        tr
          td = comment.id
          td = comment.user
          td = comment.content
          td = comment.created_at