config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users, :articles, :reports
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [:create] do
        collection do
          get 'reports', 'articles', 'show'
          post 'forgot'
          patch :update
        end
      end
      resources :accesstokens, only: [:create]
      resources :articles, only: [:index, :create] do
        post 'know'
        post 'comments'
      end
      resources :reports, only: [:create]
    end
  end

end

app/models/admin/report.rb
class Admin::Report < Report
end

app/models/report.rb
class Report < ActiveRecord::Base
  # Scope macros
  enum status: %i( processing done reject)

  # Concerns macros
  mount_uploader :pic1, ReportPicUploader
  mount_uploader :pic2, ReportPicUploader
  mount_uploader :pic3, ReportPicUploader
  # Constants

  # Attributes related macros

  # Association macros
  belongs_to :user
  
  # Validation macros
  validates :note, presence: true

  # Callbacks

  # other
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < AdminController
  before_action :set_admin_report, only: [:show, :edit, :update, :destroy]

  # GET /admin/reports
  # GET /admin/reports.json
  def index
    @admin_reports = Admin::Report.all
  end

  # GET /admin/reports/1
  # GET /admin/reports/1.json
  def show
  end

  # GET /admin/reports/new
  def new
    @admin_report = Admin::Report.new
  end

  # GET /admin/reports/1/edit
  def edit
  end

  # POST /admin/reports
  # POST /admin/reports.json
  def create
    @admin_report = Admin::Report.new(admin_report_params)

    respond_to do |format|
      if @admin_report.save
        format.html { redirect_to @admin_report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @admin_report }
      else
        format.html { render :new }
        format.json { render json: @admin_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/reports/1
  # PATCH/PUT /admin/reports/1.json
  def update
    respond_to do |format|
      if @admin_report.update(admin_report_params)
        format.html { redirect_to @admin_report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_report }
      else
        format.html { render :edit }
        format.json { render json: @admin_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/reports/1
  # DELETE /admin/reports/1.json
  def destroy
    @admin_report.destroy
    respond_to do |format|
      format.html { redirect_to admin_reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_report
      @admin_report = Admin::Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_report_params
      params.require(:admin_report).permit(:note, :location, :violate_at, :status, :region, :category, :category_other, :pic1, :pic2, :pic3)
    end
end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < Api::V1::BaseController
  before_action :authenticate!

  def create
    @report = current_user.reports.new(report_params)
    @report.violate_at -= 8.hours if @report.violate_at.present?
    
    if @report.save
      render :show, status: :created
    else
      render json: @report.errors, status: :unprocessable_entity
    end
  end

  private
    def report_params
      params.require(:report).permit(:note, :violate_at, :location, :category, :category_other, :pic1, :pic2, :pic3)
    end
end

app/views/admin/reports/_form.html.slim
= form_for(@admin_report, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @admin_report.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@admin_report.errors.count,"error")} prohibited this admin_report from being saved:"
      ul
        - @admin_report.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :category, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :category, class: "form-control"
  .form-group
    = f.label :category_other, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :category_other, class: "form-control"
  .form-group
    = f.label :region, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :region, class: "form-control"
  .form-group
    = f.label :note, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :note, class: "form-control"
  .form-group
    = f.label :location, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :location, class: "form-control"
  .form-group
    = f.label :violate_at, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :violate_at, class: "form-control"
  .form-group
    = f.label :status, class: "col-sm-2 control-label"
    .col-sm-10
      = f.select :status, Report.statuses.map{|a| [a.first, a.first]},{}, class: 'form-control'

  .form-group
    = f.label :pic1, class: "col-sm-2 control-label"
    .col-sm-10
      = f.file_field :pic1
      - if @admin_report.pic1?
        = image_tag "https://repics.storage.googleapis.com/#{@admin_report.pic1.path}"

  .form-group
    = f.label :pic2, class: "col-sm-2 control-label"
    .col-sm-10
      = f.file_field :pic2
      - if @admin_report.pic2?
        = image_tag "https://repics.storage.googleapis.com/#{@admin_report.pic2.path}"

  .form-group
    = f.label :pic3, class: "col-sm-2 control-label"
    .col-sm-10
      = f.file_field :pic3
      - if @admin_report.pic3?
        = image_tag "https://repics.storage.googleapis.com/#{@admin_report.pic3.path}"



  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/admin/reports/edit.html.slim
.page-header
  = link_to admin_reports_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @admin_report, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | admin_report

= render 'form'

app/views/admin/reports/index.html.slim
.page-header
  = link_to new_admin_report_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Report
  h1
    | Listing admin_reports

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | User
        th
          | Note
        th
          | Location
        th
          | Violate at
        th
          | Status
        th
        th
        th
    tbody
      - @admin_reports.each do | admin_report |
        tr
          td
            = link_to admin_report.user, admin_user_path(admin_report.user)
          td
            = admin_report.note
          td
            = admin_report.location
          td
            = admin_report.violate_at
          td
            = admin_report.status
          td
            = link_to 'Show', admin_report
          td
            = link_to 'Edit', edit_admin_report_path(admin_report) 
          td
            = link_to 'Destroy', admin_report, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/admin/reports/new.html.slim
.page-header
  = link_to admin_reports_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | admin_report

= render 'form'

app/views/admin/reports/show.html.slim
.page-header
  = link_to admin_reports_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_admin_report_path(@admin_report), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show admin_report
dl.dl-horizontal
  dt
    | Note:
  dd
    = @admin_report.note
  dt
    | Location:
  dd
    = @admin_report.location
  dt
    | Violate at:
  dd
    = @admin_report.violate_at
  dt
    | Status:
  dd
    = @admin_report.status