config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users, :articles, :reports
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [:create] do
        collection do
          get 'reports', 'articles', 'show'
          post 'forgot'
          patch :update
        end
      end
      resources :accesstokens, only: [:create]
      resources :articles, only: [:index, :create] do
        post 'know'
        post 'comments'
      end
      resources :reports, only: [:create]
    end
  end

end

app/models/admin/user.rb
class Admin::User < User
end

app/models/user.rb
class User < ActiveRecord::Base
  # Scope macros

  # Concerns macros
  has_secure_password

  # Constants

  # Attributes related macros

  # Association macros
  has_many :accesstokens
  has_many :articles
  has_many :reports
  
  # Validation macros
  validates :email, :name, presence: true
  validates :email, uniqueness: true

  # Callbacks

  # other

  def to_s
    name.to_s
  end

  def identity
    read_attribute(:identity) || ""
  end

  def phone
    read_attribute(:phone) || ""
  end

  def name
    read_attribute(:name) || ""
  end

  def address
    read_attribute(:address) || ""
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = Admin::User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = Admin::User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:email, :password, :password_confirmation, :name, :address, :phone, :identity)
    end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  before_action :authenticate!, only: [:update, :reports, :articles, :show]

  def create
    @user = User.new(user_params)

    if @user.save
      render :show, status: :created
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def show
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)

    if @user.update(user_params)
      render :show, status: :ok
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  def forgot
    user = User.find_by_email(@email = params[:email])
    if user 
      new_password = SecureRandom.hex(4)
      user.update_attribute(:password, new_password)
      UserMailer.forgot(user.email, new_password).deliver
    end
  end

  def reports
    @reports = current_user.reports
  end

  def articles
    @articles = current_user.articles
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :address, :phone, :identity)
    end

    def update_user_params
      user_params.except(:email)
    end
end

app/views/admin/users/_form.html.slim
= form_for(@admin_user, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @admin_user.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@admin_user.errors.count,"error")} prohibited this admin_user from being saved:"
      ul
        - @admin_user.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :email, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :email, class: "form-control"
  .form-group
    = f.label :password, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :password, class: "form-control"
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    = f.label :address, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :address, class: "form-control"
  .form-group
    = f.label :phone, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :phone, class: "form-control"
  .form-group
    = f.label :identity, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :identity, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/admin/users/edit.html.slim
.page-header
  = link_to admin_users_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @admin_user, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | admin_user

= render 'form'

app/views/admin/users/index.html.slim
.page-header
  = link_to new_admin_user_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New User
  h1
    | Listing admin_users

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Email
        th
          | Password
        th
          | Name
        th
          | Address
        th
          | Phone
        th
          | Identity
        th
        th
        th
    tbody
      - @admin_users.each do | admin_user |
        tr
          td
            = admin_user.email
          td
            = admin_user.password
          td
            = admin_user.name
          td
            = admin_user.address
          td
            = admin_user.phone
          td
            = admin_user.identity
          td
            = link_to 'Show', admin_user
          td
            = link_to 'Edit', edit_admin_user_path(admin_user) 
          td
            = link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/admin/users/new.html.slim
.page-header
  = link_to admin_users_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | admin_user

= render 'form'

app/views/admin/users/show.html.slim
.page-header
  = link_to admin_users_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_admin_user_path(@admin_user), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show admin_user
dl.dl-horizontal
  dt
    | Email:
  dd
    = @admin_user.email
  dt
    | Password:
  dd
    = @admin_user.password
  dt
    | Name:
  dd
    = @admin_user.name
  dt
    | Address:
  dd
    = @admin_user.address
  dt
    | Phone:
  dd
    = @admin_user.phone
  dt
    | Identity:
  dd
    = @admin_user.identity